### ISSUE TITLE
Better error handling when a connection is disabled

### ISSUE THREAD

**Issue by sandrinodimattia** [auth0/auth0-user-import-export-extension#14]
Steps to reproduce:

 1. Create a new connection [in the dashboard](https://manage.auth0.com/#/connections/database)
 2. Import a json file to the extension and pick the new connection
 3. This should fail because the connection is not enabled for any client:

```
Oh snap! You got an error!

An error occured while uploading the file: Request failed with status code 400
```

 4. This error is unclear. In the network trace you'll see `"errorCode": "connection_is_disabled"`. This is the real error

So instead of showing "Request failed with status code 400" we should show the following message:

`Cannot import users to a connection that is not enabled. Please (enable)(https://manage.auth0.com/#/connections/database/CONNECTION_ID_HERE/clients) at least one connection for NAME_OF_THE_CONNECTION`

**Comment by francocorreasosa** [comment]
Fixed in #15
