### ISSUE TITLE
Shows total of users when doing the export.

### ISSUE THREAD

**Issue by lobo** [auth0/auth0-user-import-export-extension#3]
<img width="689" alt="screen shot 2016-05-08 at 12 43 49 am" src="https://cloud.githubusercontent.com/assets/575750/15095884/25854512-14b6-11e6-919d-b6eaed8e23ec.png">

If I have a total of 9 users and the query that I inserted in the search bar queries 5 users, this screenshot happens.

**Comment by sandrinodimattia** [comment]
Issue has been fixed
